---

stages:
  - test
  - build-rpm
  - build-docker
  - deploy

variables:
  # This one keeps popping up again and again and again... It works locally while tox is not
  # psssing this variable to its command... That should not work at all :/
  PYCURL_SSL_LIBRARY: nss


# Use our custom image. See https://gitlab.cee.redhat.com/baseos-qe/ansible-baseos-ci/tree/master/gitlab-cicd
image: "docker-registry.upshift.redhat.com/testing-farm/baseosci-gitlab-cicd-centos7"

#
# TEST steps
#

# Run unit tests
#
# Note: this step also generates coverage report (HTML).
unit-tests:
  stage: test
  script:
    - tox -v -e py27-unit-tests -- --cov=gluetool_modules --cov-report=html:coverage-report
  artifacts:
    paths:
      - coverage-report
  tags:
    - shared

# Static analysis - pylint, flake8
static-analysis:
  stage: test
  script:
    - tox -v -e py27-static-analysis
  tags:
    - shared

# Static analysis - coala
#
# Note: coala integration is better done directly via gitlab's docker support
static-analysis-coala:
  stage: test
  image: coala/base
  script:
    - /usr/bin/coala --non-interactive --config .coafile
  tags:
    - shared

# Static analysis - type checks
type-check:
  stage: test
  script:
    - tox -v -e type-check
  tags:
    - shared

# Generate documentation from the sources
#
# Note: executed for all commits in all branches to make sure it is actually possible
# to generate the documentation - serves as a sort of a "test" on its own. citool
# uses docstrings to generate command-line help, it is useful to check whether these
# docstrings are readable and sane.
generate-docs:
  stage: test
  script:
    - tox -v -e py27-doctest -- ./docs
  artifacts:
    paths:
      - .tox/py27-doctest/tmp/docs/build/html
  tags:
    - shared


#
# BUILD steps
#

# Trigger RPM build
build-rpm-packages:
  stage: build-rpm
  only:
    - master@baseos-qe/gluetool-modules
  script:
    - tower-cli job launch --monitor -J "[BaseOS CI] [build] [rpm] citool-modules-full"
  tags:
    - shared

build-rpm-packages-devel:
  stage: build-rpm
  only:
    - devel@baseos-qe/gluetool-modules
  script:
    - tower-cli job launch --monitor -J "[BaseOS CI] [build] [rpm] citool-modules-full-devel"
  tags:
    - shared

# Trigger Docker build
build-docker-images:
  stage: build-docker
  only:
    - master@baseos-qe/gluetool-modules
  script:
    - tower-cli workflow_job launch --monitor -W "[BaseOS CI] [build] [docker] Production chain" | tee tower_output.log
    - grep 'failed' tower_output.log && { echo 'At least one of subtasks failed!'; exit 1; } || exit 0
  tags:
    - shared

build-docker-images-devel:
  stage: build-docker
  only:
    - devel@baseos-qe/gluetool-modules
  script:
    - tower-cli workflow_job launch --monitor -W "[BaseOS CI] [build] [docker] Devel chain" | tee tower_output.log
    - grep 'failed' tower_output.log && { echo 'At least one of subtasks failed!'; exit 1; } || exit 0
  tags:
    - shared

# Trigger staging deployment
deploy-to-staging:
  stage: deploy
  only:
    - devel@baseos-qe/gluetool-modules
  script:
    - tower-cli workflow_job launch --monitor -W "[BaseOS CI] [deploy] [staging] Image" | tee tower_output.log
    - grep 'failed' tower_output.log && { echo 'At least one of subtasks failed!'; exit 1; } || exit 0

  tags:
    - shared
