before_script:
    - yum -y install git make python-setuptools gcc python-devel krb5-devel
    - git clone https://pagure.io/koji.git ~/koji
    - (cd ~/koji/koji && make install)

tests:
  script:
    - python setup.py test
