before_script:
    - yum -y install git make python-setuptools gcc python-devel krb5-devel postgresql-devel
    - (curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" && python get-pip.py && rm -f get-pip.py)
    - pip install -U setuptools
    - pip install tox

tests:
  script:
    - tox -e py27

build:
  script:
    - pip install copr copr-cli simplejson
    # we need to use python-requests from rpm to have update-ca-trust to work
    - pip uninstall -y requests
    - yum -y install python-requests rpm-build
    # this script was developed for Common Criteria Certification and is used for a few python tools
    - curl -so /usr/bin/build_python_project http://cc-git.lab.eng.brq.redhat.com/cgit/gov-cert-tools/plain/tools/build_python_project
    - chmod +x /usr/bin/build_python_project
    # RH IT Root CA is required for copr to work
    - curl -sko /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt https://password.corp.redhat.com/RH-IT-Root-CA.crt
    - update-ca-trust
    # add copr config for the jenkins/baseos-jenkins.rhev-ci-vms.eng.rdu2.redhat.com@REDHAT.COM user 
    - mkdir ~/.config
    - echo "W2NvcHItY2xpXQpsb2dpbiA9IFkyOXdjZz09IyNpbXZ4eWZibHFoa2dybWdzdHlmaAp1c2VybmFtZSA9IGplbmtpbnNfYmFzZW9zLWplbmtpbnMucmhldi1jaS12bXMuZW5nLnJkdTIucmVkaGF0LmNvbQp0b2tlbiA9IHJqb29lcmN2ZHdrcnh1eGptYmJ1YXNvb2lzdGp3bApjb3ByX3VybCA9IGh0dHBzOi8vY29wci5kZXZlbC5yZWRoYXQuY29tCg==" | base64 -d > ~/.config/copr
    - cat ~/.config/copr
    - build_python_project
  only:
    - master
